force_shop/urls.py
# coding=utf-8
# author: dlyapun

from django.conf.urls import url, include
from force_shop.views import *
from force_shop.api import *


urlpatterns = [
    url(r'^$', ListProductView.as_view(), name="list-shop-url"),
    url(r'^order/$', OrderView.as_view(), name="order"),
    url(r'^pay/$', PayOrderView.as_view(), name="pay"),
    url(r'^cart/$', CartView.as_view(), name="cart-page-url"),
    url(r'^add_to_cart/$', AddToCartView.as_view(), name='add-to-cart-url'),
    url(r'^remove/(?P<product_id>[\w-]+)/$', RemoveProductFromCart.as_view(), name='remove-product-cart-url'),
    url(r'^(?P<meta_url>[\w-]+)/$', DetailProductView.as_view(), name="detail-product-url"),
    url(r'^category/(?P<category_slug>[\w-]+)/$', CategoryListView.as_view(), name="category-list-url"),
    url(r'^search$', SearchProductView.as_view(), name='product-search')
]

# API
urlpatterns += [
    url(r'^api/v1/products-list/$', ProductListView.as_view(), name='products-list-api'),
    url(r'^api/v1/product-add/$', ProductAddView.as_view(), name='product-add-api'),
    url(r'^api/v1/product-remove/$', ProductRemoveView.as_view(), name='product-remove-api'),
]

project/urls.py
# coding=utf-8

from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.views.generic import RedirectView, TemplateView


urlpatterns = [
    url(r'^$', RedirectView.as_view(url='/shop/?count=12'), name='blog'),
    url(r'^shop/', include('force_shop.urls')),
    url(r'^accounts/', include('accounts.urls')),
    url(r'^admin/', include(admin.site.urls)),
]

if settings.DEBUG:
    urlpatterns += [
    ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += [
    ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

    import debug_toolbar
    urlpatterns += [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ]

urlpatterns += staticfiles_urlpatterns()

# python -m smtpd -n -c DebuggingServer localhost:1025

force_shop/forms.py
# coding=utf-8
# author: dlyapun

from django import forms
from django.forms import ModelForm
from .models import Order, Currency


class AddProductForm(forms.Form):
    quantity = forms.IntegerField()


class OrderForm(ModelForm):
    class Meta:
        model = Order
        exclude = ['user_id' ,'date_creation', 'cart', 'transaction_id', 'status_payment', 'status_shipping', 'price_captured', 'shipping_price', 'tax_price', 'total_price', 'currency']

    def save(self, *args, **kwargs):
        cart = kwargs.pop('cart')
        user_id = kwargs.pop('user_id')
        obj = super(OrderForm, self).save(commit=False)
        obj.user_id = user_id
        obj.currency = Currency.get_default()
        obj.cart = cart
        obj.save()
        obj.calculate_prices()
        return obj

force_shop/views.py
# coding=utf-8
# author: dlyapun

from django.contrib.auth.decorators import login_required
from django.db.models import Q
from django.shortcuts import render_to_response
from django.views import View

from .cart import Cart
from .forms import AddProductForm, OrderForm
from .models import Product, Order, Category, ProductVariation, Shipping

from django.shortcuts import redirect
from django.views.generic import TemplateView, DetailView, FormView
from django.views.decorators.cache import never_cache


DISABLE = 0
ENABLE = 1

LIMIT_OBJECTS = 72


class BaseProductView(TemplateView):
    template_name = 'force_shop/list_shop.html'

    @never_cache
    def get(self, request, *args, **kwargs):
        context = self.get_context_data(**kwargs)
        return self.render_to_response(context)

    def get_context_data(self, **kwargs):
        context = super(BaseProductView, self).get_context_data(**kwargs)

        request_count = self.request.GET.get('count', '12')
        products_count = int(request_count) if request_count.isdigit() else LIMIT_OBJECTS

        sorted_field = self.request.GET.get('s', 'rating')
        context['sort_by'] = sorted_field
        context['products'] = Product.get_sorted_products(sorted_field)[:products_count]
        context['path_products_count_in_page'] = products_count
        return context


class ListProductView(BaseProductView):
    pass


class CategoryListView(TemplateView):
    template_name = 'force_shop/list_shop.html'

    def get_context_data(self, **kwargs):
        context = super(CategoryListView, self).get_context_data(**kwargs)
        request_count = self.request.GET.get('count', 12)
        sorted_field = self.request.GET.get('s', 'rating')
        category = kwargs.get('category_slug')

        # products_count = int(request_count) if request_count.isdigit() else LIMIT_OBJECTS
        context['products'] = Product.get_products_by_category(category)
        context['category'] = Category.get_by_slug(category)
        return context


class DetailProductView(DetailView):
    model = Product
    context_object_name = 'product'
    template_name = 'force_shop/detail_shop.html'

    def get_object(self, queryset=None):
        return Product.get_by_slug(self.kwargs.get('meta_url'))

    def get_context_data(self, **kwargs):
        context = super(DetailProductView, self).get_context_data(**kwargs)
        context['product_variations'] = self.object.variations.all()
        return context


class AddToCartView(FormView):
    """Add to cart logic"""
    form_class = AddProductForm
    success_url = '/shop/cart'

    def form_valid(self, form):
        # get item quantity and find product by id then add to cart
        quantity = form.cleaned_data['quantity']
        product = ProductVariation.get_by_id(self.request.POST['product_id'])   # get product by id
        Cart(self.request).add(product, quantity)
        return super(AddToCartView, self).form_valid(form)


class RemoveProductFromCart(View):

    def get(self, *args, **kwargs):
        product = ProductVariation.get_by_id(kwargs.get('product_id'))
        cart = Cart(self.request)
        cart.remove(product)
        return redirect('/shop/cart/')


class CartView(DetailView):

    model = Cart
    context_object_name = 'cart'
    template_name = 'force_shop/cart.html'

    def get_object(self, queryset=None):
        return Cart(self.request)


class OrderView(FormView):

    template_name = 'force_shop/order.html'
    form_class = OrderForm

    def get_initial(self):
        initial = super(OrderView, self).get_initial()
        if self.request.user.is_authenticated:
            initial['order_first_name'] = self.request.user.first_name
            initial['order_last_name'] = self.request.user.last_name
            initial['order_email'] = self.request.user.email
            # TODO: Improve Address field for user where we can store billing informatin and phone
        return initial

    def get_context_data(self, **kwargs):
        context = super(OrderView, self).get_context_data(**kwargs)
        context['cart'] = Cart(self.request)
        context['shippings'] = Shipping.get_enable_shippings()
        return context

    def post(self, *args, **kwargs):
        form = OrderForm(self.request.POST)  # Проверить
        if form.is_valid():
            user_id = self.request.user.id if self.request.user.is_authenticated else None
            cart = Cart(self.request).get_cart(self.request)
            cart.save()
            form.save(cart=cart, user_id=user_id)
            Cart(self.request).new(self.request)
            url = '/shop/pay/'
            return redirect(url)
        return super(OrderView, self).post(*args, **kwargs)


class PayOrderView(TemplateView):
    template_name = 'force_shop/pay.html'

    def get_context_data(self, **kwargs):
        context = super(PayOrderView, self).get_context_data(**kwargs)
        context['form'] = OrderForm()
        return context


class SearchProductView(BaseProductView):
    template_name = 'force_shop/list_shop.html'

    def get_queryset(self):
        qs = Product.get_default_query()

        keywords = self.request.GET.get('q')
        if keywords:
            # TODO: use postgres for local dev
            # full text search for postgres db
            # query = SearchQuery(keywords)
            # vector = SearchVector('name', 'text')
            # qs = qs.annotate(search=vector).filter(search=query)
            # qs = qs.annotate(rank=SearchRank(vector, query))
            qs = qs.filter(Q(name__icontains=keywords) | Q(text__icontains=keywords))
        return qs

    def get_context_data(self, **kwargs):
        context = super(SearchProductView, self).get_context_data(**kwargs)
        context['products'] = self.get_queryset()
        return context

force_shop/templates/force_shop/details/grid_detail.html
{% load force_shop_tags %}

<div class="row" id="details">
    <div class="col-md-12 col-sm-12"><h4 id="productDetails">Product details</h4></div>
    {% for product_variation in product_variations %}
        <form action="/shop/add_to_cart/" class="form-inline" method="post" role="form">{% csrf_token %}
        <div class="col-md-4 col-sm-6">
            <div class="product">
                <div class="product-img"><a href="{{ product_variation.get_absolute_url }}">
                    <img src="{{ product_variation.current_image }}" alt="" >
                    </a>
                </div>
                <div class="text">
                    <h3><a href="{{ product_variation.get_absolute_url }}">{{ product_variation.code }}</a></h3>
                    <input type="hidden" name="product_id" value="{{ product_variation.id }}" /><br>

                    <p class="price">
                        <select id="id_quantity" name="quantity" class="form-control" style="margin: 0 5px 0 0">
                            {% for i in product_variation.count|create_range %}
                            <option value="{{ i }}">{{ i }}</option>
                            {% endfor %}
                        </select>
                        {% if product_variation.price_sale %}<del>{{ product_variation.product_price_sale }}</del> {% endif %}{{ product_variation.product_price }}
                    </p>
                    <p class="buttons">
                        <button type="submit" class="btn btn-block btn-primary"><i class="fa fa-shopping-cart"></i>Купить</button>

                    </p>
                </div>
                {% if product_variation.discount %}
                <div class="ribbon sale">
                    <div class="theribbon">SALE</div>
                    <div class="ribbon-background"></div>
                </div>
                {% endif %}
                {% if product_variation.product_value_new %}
                <div class="ribbon new">
                    <div class="theribbon">NEW</div>
                    <div class="ribbon-background"></div>
                </div>
                {% endif %}
            </div>
        </div>
    </form>
    {% endfor %}
</div>

force_shop/templates/force_shop/details/layer_detail.html
{% load force_shop_tags %}

<div class="box" id="details">
    <h4>Product details</h4>
    <form action="/shop/add_to_cart/" class="form-inline" method="post" role="form">{% csrf_token %}
        <div class="form-group">
            <select class="form-control" name="product_id">
                {% for product_variation in product_variations %}
                    <option value="{{ product_variation.id }}">{{ product_variation.variations.all }}: {{ product_variation.price }}</option>
                {% endfor %}
            </select>
        </div>
        <div class="form-group">
            <label for="exampleInputEmail2">quantity</label>
            <select class="form-control" name="quantity">
                <option value="1">1</option>
                <option value="2">2</option>
                <option value="3">3</option>
                <option value="4">4</option>
                <option value="5">5</option>
            </select>
        </div>
        <button type="submit" class="btn btn-primary"><i class="fa fa-shopping-cart"></i>Купить</button>
    </form>
</div>